/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.0.111.2 */
/* Module Version: 5.7 */
/* Sat May 18 20:54:32 2019 */

/* parameterized module instance */
Clock_DCMA __ (.CLKI( ), .CLKOP( ));
